### ISSUE TITLE
Builds & Flashes but doesn't Run

### ISSUE THREAD

**Issue by niabassey** [particle-iot/snowflake#8]
Building this from source in Particle Workbench gets as far as a successful build and flash and when the flash finishes the P2 even connects to WiFi, but that's it.  The LED animation stays frozen in it's last state and there no serial output (usually it give TFLite stats).

Flashing using https://setup.particle.io/?app=particle-snowflake brings it back up, but half the fun is getting to code this thing.

Are there particular build instructions to get a working locally built firmware image?

**Comment by svanhoutte** [comment]
@niabassey How did you manage to compile, I get a SRAM overflowed. I m trying the 5.6.0 firmware, and code straight from the repo. I tried in the workbench and on docker same error. 

> /root/.particle/toolchains/gcc-arm/10.2.1/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /workspace/target/workspace_fi.elf section `.bss' will not fit in region `SRAM'
/root/.particle/toolchains/gcc-arm/10.2.1/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: region `SRAM' overflowed by 4 bytes
collect2: error: ld returned 1 exit status
make[1]: Leaving directory `/firmware/modules/tron/user-part'
make[1]: *** [/workspace/target/workspace_fi.elf] Error 1
make: *** [modules/tron/user-part] Error 2

**Comment by niabassey** [comment]
I was able to compile on Windows but the application doesn't run.  I tried on Ubuntu and I got the same SRAM overflowed error :(

**Comment by jhewitt0** [comment]
I'm unable to compile on Windows 11 using CLI or Workbench. Help please...

`particle compile p2 . --saveTo firmware.zip --target 5.5.0`
> Compile failed: Compiler timed out or encountered an error

If I tell Workbench to do a Cloud Compile I just get
> Compile failed: Compiler timed out or encountered an error
	at makeError (c:\Users\j_hew\.vscode\extensions\particle.particle-vscode-core-1.16.13\node_modules\execa\lib\error.js:59:11)
	at handlePromise (c:\Users\j_hew\.vscode\extensions\particle.particle-vscode-core-1.16.13\node_modules\execa\index.js:114:26)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


What is the correct way to compile the code?

Thanks

**Comment by svanhoutte** [comment]
@jhewitt0 you should try a local compile from the bench.

**Comment by mrlambchop** [comment]
Hey folks, 

Apologies - there is a random bug in the makefile that breaks the compilation at semi-random. 

We have a pending release that fixes this but it got stuck behind the holidays - not great timing I know.

To work around this, you can:

- clone device OS GitHub repo into a local folder
- git checkout -b fix/ram-calc-section-alignment origin/fix/ram-calc-section-alignment
- git submodules init
- git submodule update --recursive

Then open the project in Workbench and in the settings, set the setting:

Particle: Custom Device OSLocation to the path. Make sure the path is fully qualified. 

Then in workbench, you can compile / flash the project and it won't randomly fail. I'll post back when the device OS release is out.

Thanks

Nick.

**Comment by svanhoutte** [comment]
@mrlambchop I confirm the workaround works. 
This link help to get the workbench setup. https://docs.particle.io/getting-started/developer-tools/workbench-faq/
